name: SuperScrapTest
favicon: null
layout_spectrum: 0.26782
typography_spectrum: 0.62873
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2f2f2f'
    - '#ececec'
    - '#f3d824'
    - '#717171'
    - '#1b95e0'
  brandStrength: 0.5
  lightness: 0.7166856718249619
  saturation: 0.6594694617670029
  rhythmicContrast: 0.15902110445313156
purpose: []
